#!/usr/bin/env perl
package Pgtools::pg_kill;

use 5.021;
use strict;
use warnings;
use Data::Dumper;
use Getopt::Long qw(:config posix_default no_ignore_case gnu_compat);
use Perl6::Slurp;
use JSON::XS;
use Mod::Kill;
use Mod::Connection;

our $VERSION = '0.0.1';
$| = 1; # auto-flush STDOUT

my $opt = {
    "help"                   => 0,
    "ignore_match_query"     => '',
    "ignore_match_state"     => '',
    "ignore_query_user_name" => '',
    "kill"                   => '',
    "match_query"            => '',
    "match_state"            => '',
    "print"                  => 0,
    "query_user_name"        => '',
    "run_time"               => 0,
    "version"                => 0,
};

GetOptions(
    'help|h'                     => \$opt->{help},
    "ignore_match_query|imq=s"   => \$opt->{ignore_match_query},
    "ignore_match_state|ims=s"   => \$opt->{ignore_match_state},
    "ignore_query_user_name|iun=s" => \$opt->{ignore_query_user_name},
    'kill'                       => \$opt->{kill},
    'match_query|mq=s'           => \$opt->{match_query},
    'match_state|ms=s'           => \$opt->{match_state},
    'print|pr'                   => \$opt->{print},
    'query_user_name|un=s'       => \$opt->{query_user_name},
    'run_time|r=i'               => \$opt->{run_time},
    'version|v'                  => \$opt->{version},
);

# show help 
if($opt->{help}){
    &print_help;
    exit;
}
if($opt->{version}){
    print "Version: ".$VERSION."\n";
    exit;
}

if (@ARGV != 1) {  
    die "Invalid arguments.\nPlease check pg_config_diff -help\n";
}

my $s = Kill->new($opt);
$s->exec();


sub print_help {
    print <<OUT;
    $0 -help | [-(options below)]

    Kill queries which are matched specified regular expression.

  Options:
    -db  database:       set the database name
    -h   host:           host (localhost)
    -help:               show this help
    -ignore_match_query: except matching query
    -ignore_match_state: except matching state
    -kill:               kill query which matched condition
    -mq  match_query:    query match
    -ms  match_state:    state match
    -pr  print:          print killed queries info
    -p   passward:       set password
    -port:               port number
    -query_user_name:     user who exec query
    -r   run_time:       execute time 
    -u   user:           Postgres user name 
    -v   version:        version
OUT
}


__END__


=head1 NAME

Pgtools::pg_kill - kill the postgresql processes with option 

=head1 SYNOPSIS

    Kill PostgreSQL queries accurately with some options.

Perhaps a little code snippet.

    ...
    ...

    Kill queries which are matched specified regular expression and the other options.

  Options:
    -db  database:       set the database name
    -h   host:           host (localhost)
    -help:               show this help
    -ignore_match_query: except matching query
    -ignore_match_state: except matching state
    -kill:               kill query which matched condition
    -mq  match_query:    query match
    -ms  match_state:    state match
    -pr  print:          print killed queries info
    -p   passward:       set password
    -port:               port number
    -query_user_name:     user who exec query
    -r   run_time:       execute time 
    -u   user:           Postgres user name 
    -v   version:        version


=head1 AUTHOR

Tomoaki Otsuka, C<< <otsuka.tt at gmail.com> >>

=head1 BUGS

Please report any bugs or feature requests to C<bug-./ at rt.cpan.org>, or through
the web interface at L<http://rt.cpan.org/NoAuth/ReportBug.html?Queue=./>.  I will be notified, and then you'll
automatically be notified of progress on your bug as I make changes.


=head1 SUPPORT

You can find documentation for this module with the perldoc command.

    perldoc Pgtools::pg_kill


You can also look for information at:

=over 4

=item * RT: CPAN's request tracker (report bugs here)

L<http://rt.cpan.org/NoAuth/Bugs.html?Dist=./>

=item * AnnoCPAN: Annotated CPAN documentation

L<http://annocpan.org/dist/./>

=item * CPAN Ratings

L<http://cpanratings.perl.org/d/./>

=item * Search CPAN

L<http://search.cpan.org/dist/.//>

=back


=head1 ACKNOWLEDGEMENTS


=head1 LICENSE AND COPYRIGHT

Copyright 2016 Tomoaki Otsuka.

This program is free software;
=cut

1; # End of Pgtools::pg_kill
